### ISSUE TITLE
How can I get other files?

### ISSUE THREAD

**Issue by lrongzheni** [lylylylylyly/SimpleFSRE#2]
> /data/lirongzhen/SimpleFSRE/fewshot_re_kit/data_loader.py(503)__init__()
-> print("[ERROR] Data file does not exist!")
(Pdb) p path
'./data/5-1-test.json'
(Pdb) c
[ERROR] Data file does not exist!
Traceback (most recent call last):
  File "train_demo.py", line 325, in <module>
    main()
  File "train_demo.py", line 216, in main
    N=N, K=K, Q=Q, na_rate=opt.na_rate, batch_size=batch_size)
  File "/data/lirongzhen/SimpleFSRE/fewshot_re_kit/data_loader.py", line 659, in get_loader2
    dataset = FewRelTestDataset(name, encoder, N, K, Q, na_rate, root)
  File "/data/lirongzhen/SimpleFSRE/fewshot_re_kit/data_loader.py", line 503, in __init__
    print("[ERROR] Data file does not exist!")
AssertionError

**Comment by lyyang01** [comment]
> 
hi, you can see the Data and Models section to get FewRel 1.0 dataset first.

**Comment by baommmmmm** [comment]
hi，how can me get test data?
