### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by HeTaoya** [lylylylylyly/SimpleFSRE#6]
当我在训练时，train——demo.py文件317行训练模型时出现错误：它提示我使用的proto_7_2.py文件的82行使用的句子编码器中的163行（x=self.bert...）出现错误，原因为：元组的索引应该是整数或者切片，不应该是字符串

**Comment by HeTaoya** [comment]
我不太清楚这是一个什么原因，有时候它也报错，too many values to unpack

**Comment by lyyang01** [comment]
你好，这看起来像是transformers版本的问题，可以检查一下transformers版本是不是4.6.0

**Comment by HeTaoya** [comment]
确实是这个问题，谢谢

**Comment by 123xxxbg** [comment]
您好，在我运行train_demo.py文件时，出现了Traceback (most recent call last):
  File "D:\code_ner\SimpleFSRE-main\SimpleFSRE-main\train_demo.py", line 325, in <module>
    main()
  File "D:\code_ner\SimpleFSRE-main\SimpleFSRE-main\train_demo.py", line 213, in main
    val_data_loader = get_loader(opt.val, sentence_encoder,
  File "D:\code_ner\SimpleFSRE-main\SimpleFSRE-main\fewshot_re_kit\data_loader.py", line 151, in get_loader
    dataset = FewRelDataset(name, encoder, N, K, Q, na_rate, root)
  File "D:\code_ner\SimpleFSRE-main\SimpleFSRE-main\fewshot_re_kit\data_loader.py", line 21, in __init__
    assert(0)
AssertionError这个问题，请问是什么原因呀
